- name: ping the servers 
  hosts: webserver
  tasks:
    - name: ping the servers
      ansible.builtin.ping:
    - name:  Hello world
      ansible.builtin.debug:
        msg: "Hello world"
      

        